---
- name: Download docker-compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "/usr/bin/docker-compose-{{ docker_compose_version }}"
    owner: root
    group: docker
    mode: '0755'

- name: create symlink
  file:
    src: "/usr/bin/docker-compose-{{ docker_compose_version }}"
    dest: /usr/bin/docker-compose
    state: link
    owner: root
    group: docker
    mode: '0755'
    force: yes