- name: Add Plex repo
  yum_repository:
    name: "{{ plex_repo.name }}"
    baseurl: "{{ plex_repo.baseurl }}"
    description: "{{ plex_repo.description }}"
    gpgcheck: "{{ plex_repo.gpgcheck }}"
    gpgkey: "{{ plex_repo.gpgkey }}"

- name: Install Docker package
  package:
    name: "{{ plex_package }}"

- name: Replace service file
  template:
    src: plexmediaserver.service.j2
    dest: /usr/lib/systemd/system/plexmediaserver.service
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Reload sytemctl daemon
  shell: "systemctl daemon-reload"

- name: "Create tmp directory"
  file:
    path: "/multimedia/plex_tmp"
    state: directory
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0755"

- name: Start Plex
  service:
    name: "{{ plex_package }}"
    state: restarted
