- hosts: seedbox

  roles:

  - { role: users/admin_user,
      admin_user: "{{ my_admin_user }}"
    }
  - { role: users/limited_user,
      user: "{{ common_user }}",
    }
  - { role: tools/common_storage,
      user: "{{ common_user.username }}",
      group: "{{ common_user.group }}"
    }
  - { role: services/plex,
      username: "{{ common_user.username }}",
      group: "{{ common_user.group }}"
    }
  - services/docker
  - { role: services/transmission,
      uid: "{{ common_user.uid }}",
      gid: "{{ common_user.gid }}"
    }
  - { role: services/sickrage,
      user: "{{ common_user }}"
    }
  - services/apache