- name: "Check if service file exists"
  stat:
    path: "/etc/systemd/system/{{ instance_name }}.service"
  register: service_file

- name: "Stop Apache"
  service:
    name: "{{ instance_name }}.service"
    state: stopped
  when: service_file.stat.exists
