---

- name: "Create group: {{ user.group }} with GID {{ user.gid }}"
  group:
    name: "{{ user.group }}"
    gid: "{{ user.gid }}"
    state: present
  when: user.group is defined and user.gid is defined

- name: "Create user: {{ user.username }} with UID {{ user.uid }}"
  user:
    name: "{{ user.username }}"
    uid: "{{ user.uid }}"
    group: "{{ user.group }}"
  when: user.group is defined and user.uid is defined

- name: "Create user: {{ user.username }} "
  user:
    name: "{{ user.username }}"
  when: not user.uid is defined and not user.group is defined

- name: "{{ user.username }} ssh directory"
  file:
    path: "/home/{{ user.username }}/.ssh"
    state: directory
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: "0700"

- name: "Checking if the authorized keys file exists"
  stat:
    path: "/home/{{ user.username }}/.ssh/authorized_keys"
  register: auth_keys_stat

- name: "Create authorized keys file"
  file:
    path: "/home/{{ user.username }}/.ssh/authorized_keys"
    state: touch
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: "0600"
  when: auth_keys_stat.stat.exists == False

- name: "Add authorized_keys"
  lineinfile:
    dest: "/home/{{ user.username }}/.ssh/authorized_keys"
    line: "{{ item }}"
  with_items: "{{user.authorized_keys | default ([]) }}"


